# Generated by Django 4.0.5 on 2022-06-06 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderBoards', '0002_leaderboard_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboarditem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
