# Generated by Django 4.0.5 on 2022-06-07 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderBoards', '0004_leaderboard_ownername'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboarditem',
            options={'ordering': ['score']},
        ),
    ]
