# Generated by Django 4.0.5 on 2022-06-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderBoards', '0005_alter_leaderboarditem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboarditem',
            options={'ordering': ['-score']},
        ),
    ]
