# Generated by Django 4.0.5 on 2022-06-06 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=200, null=True, unique=True)),
                ('visibility', models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderBoardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoreHolder', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('phrase', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('LeaderBoard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderBoardItems', to='leaderBoards.leaderboard')),
            ],
        ),
    ]
