# Generated by Django 4.0.5 on 2022-06-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderBoards', '0003_alter_leaderboarditem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='ownerName',
            field=models.CharField(default='WazaBanda', max_length=150),
            preserve_default=False,
        ),
    ]
